[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "contracts/test"
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.default.fuzz]
runs = 256

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
